spring:
  datasource:
#    url:
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/league?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: kim2299
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100



server:
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.hibernate_SQL: debug
